export { default } from 'next-auth/middleware'

export const config = {
  matcher: [
    '/dashboard/:path*',
    '/establishment-vacancies/:path*',
    '/advertisements/:path*',
    '/applications/:path*',
    '/shortlisting/:path*',
    '/interviews-tests/:path*',
    '/verification/:path*',
    '/appointment-letters/:path*',
    '/onboarding-oath/:path*',
    '/probation/:path*',
    '/employee-records/:path*',
    '/leave/:path*',
    '/discipline-grievance/:path*',
    '/payroll-certification/:path*',
    '/reports-compliance/:path*',
    '/audit-log/:path*',
    '/integrations/:path*',
    '/settings-reference-data/:path*',
    '/recruitment/:path*',
    '/employees/:path*',
    '/onboarding/:path*',
    '/performance/:path*',
    '/analytics/:path*',
    '/ai-assistant/:path*',
    '/company/:path*',
    '/api/jobs/:path*',
    '/api/candidates/:path*',
    '/api/employees/:path*',
    '/api/performance/:path*',
    '/api/analytics/:path*',
    '/api/ai/:path*',
    '/api/company/:path*',
    '/api/upload/:path*',
    '/api/communications/:path*',
    '/api/onboarding/:path*',
    '/api/dsc/:path*',
  ],
}
